<a href="https://colab.research.google.com/github/vrinda561/Human-activity-recognition-using-smartwatch/blob/main/Logisticregression.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# LOGISTIC REGRESSION 

IMPORTING DATASET

In [ ]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

IMPORTING DATASET

In [ ]:
dataset = pd.read_csv("Human_Activity_Recognition_Using_Smartphones_Data.csv")
x = dataset.iloc[1:,:-1].values
y = dataset.iloc[1:,-1].values

ENCODING CATEGORICAL DATA

In [ ]:
from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()
y = le.fit_transform(y)
print(y)

[2 2 2 ... 5 5 5]


SPLITTING DATASET IN TRAINING AND TESTING SET

In [ ]:
from sklearn.model_selection import train_test_split
x_train,x_test, y_train, y_test = train_test_split(x,y,test_size= 0.2, random_state =1)

TRAINING LOGISTIC REGRESSION MODEL ON TRAINING SET

In [ ]:
from sklearn.linear_model import LogisticRegression
classifier = LogisticRegression()
classifier.fit(x_train,y_train)

/usr/local/lib/python3.7/dist-packages/sklearn/linear_model/_logistic.py:818: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  extra_warning_msg=_LOGISTIC_SOLVER_CONVERGENCE_MSG,


LogisticRegression()

PREDICTING THE TEST SET RESULT AND COMPARING 

In [ ]:
y_pred = classifier.predict(x_test)
df = pd.DataFrame({'Real_Values':y_test.reshape(-1),'Predicte_Values':y_pred})
print(df)

      Real_Values  Predicte_Values
0               5                5
1               2                2
2               2                2
3               5                5
4               0                0
...           ...              ...
2055            5                5
2056            0                0
2057            3                3
2058            2                2
2059            3                3

[2060 rows x 2 columns]


CONFUSION MATRICE AND ACCURACY

In [ ]:
from sklearn.metrics import confusion_matrix,accuracy_score
cm = confusion_matrix(y_test,y_pred)
print(cm)
accuracy_score(y_test,y_pred)

[[361   0   0   0   0   0]
 [  0 339  13   0   0   0]
 [  0  18 366   0   0   0]
 [  0   0   0 349   1   0]
 [  0   0   0   1 288   1]
 [  0   0   0   0   2 321]]


0.9825242718446602